install(DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/locale/"
        DESTINATION ${CMAKE_INSTALL_LOCALEDIR})

install(TARGETS binsearch RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
install(TARGETS binsearchlib
        LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} PUBLIC_HEADER_DESTINATTION
                                                    ${CMAKE_INSTALL_INCLUDEDIR})

install(DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/docs/man" DESTINATION ${CMAKE_INSTALL_DATAROOTDIR})